name: "编译内核"

on:
  workflow_dispatch:
    inputs:
      AUTHOR:
        description: 'AUTHOR'
        required: true
        default: 'PPKunOfficial'   
      CHECKOUT_REPO:
        description: 'CHECKOUT_REPO'
        required: true
        default: 'android_kernel_xiaomi_sdm845'
      CHECKOUT_BRANCH:
        description: 'CHECKOUT_BRANCH'
        required: true
        default: 'rebase-s'
      USEDEFCONFIG:
        description: 'USEDEFCONFIG'
        required: true
        default: 'dipper_defconfig'

env:
  CLANG_VER: 'proton-clang'
  ARCHOSUB: 'arm64'
  KERNEL_DIR: 'kernel_source'

jobs:
  compile:
    name: 编译内核
    runs-on: ubuntu-latest
    steps:
    - name: 拉取模板
      uses: actions/checkout@v3
      with:
        path: Anykernel

    - name: 准备编译环境
      run: |
        sudo apt update -y
        sudo apt install -y git wget unzip p7zip-full git
        
    - name: 打包内核
      run: |
        cd ${{ github.workspace }}/Anykernel
        ls
        zip -o Kernel_template.zip
        ls
        zip -q -r output.zip ${{ github.workspace }}/Anykernel/Kernel_template
        ls

    - name: 上传到网盘
      run: |
        sudo apt install curl
        curl -sL https://git.io/file-transfer | sh 
        ./transfer arp ${{ github.workspace }}/Anykernel/output.zip --silent
    